main/urls.py
from django.urls import path,re_path
from . import views

app_name = 'main'

urlpatterns = [
    path('', views.index,name='index'),
]

property/urls.py
from django.urls import path,re_path
from . import views

app_name = 'property'

urlpatterns = [
    path('list/', views.property_list, name='property_list'),
    re_path(r'^create-property/$', views.create_property, name='create_property'),
    re_path(r'^property-info/(?P<pk>.*)/$', views.property_info, name='property_info'),
    re_path(r'^edit-property/(?P<pk>.*)/$', views.edit_property, name='edit_property'),
    re_path(r'^delete-property/(?P<pk>.*)/$', views.delete_property, name='delete_property'),
    re_path(r'^assign-property/(?P<unit_id>.*)/$', views.assign_property_tenant, name='assign_property_tenant'),
]

real_estate/urls.py
from django.contrib import admin
from django.urls import path
from django.views.static import serve
from django.urls import  include, path, re_path

from real_estate import settings
from main import views as general_views

urlpatterns = [
    path('',include(('main.urls'),namespace='main')),
    path('admin/', admin.site.urls),
    path('app/accounts/', include('registration.backends.default.urls')),
    path('super-admin/main/',general_views.app,name='app'),
    
    path('super-admin/admin-user/',include(('admin_user.urls'),namespace='admin_user')),
    path('super-admin/property/',include(('property.urls'),namespace='property')),
    path('super-admin/tenant/',include(('tenant.urls'),namespace='tenant')),
    
    re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
    re_path(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT})
]

property/models.py
import uuid

from django.db import models
from django.contrib.auth.models import User

from decimal import Decimal
from ckeditor.fields import RichTextField
from versatileimagefield.fields import VersatileImageField

UNIT_TYPES = (
    ('010', '1BHK'),
    ('015', '2BHK'),
    ('020', '3BHK'),
    ('025', '4BHK'),
    ('030', '5BHK'),
    ('035', '6BHK'),
)

# Create your models here.
class Property(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    name = models.CharField(max_length=200)
    address = models.TextField()
    features = RichTextField()
    location = models.CharField(max_length=256)
    image = VersatileImageField('Image', upload_to="propertes/property", blank=True, null=True)
    is_deleted = models.BooleanField(default=False)
    
    class Meta:
        db_table = 'properties'
        verbose_name = ('Property')
        verbose_name_plural = ('Property')
        
    def __str__(self):
        return str(self.id)

class Unit(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    type = models.CharField(max_length=3, choices=UNIT_TYPES)
    rent_cost = models.DecimalField(default=0, max_digits=10, decimal_places=2)
    main_image = VersatileImageField('Image', upload_to="units/main_images", blank=True, null=True)
    is_deleted = models.BooleanField(default=False)
    
    property = models.ForeignKey(Property, on_delete=models.CASCADE)
    
    class Meta:
        db_table = 'units'
        verbose_name = ('Unit')
        verbose_name_plural = ('Unit')
        
    def __str__(self):
        return str(self.id)

property/forms.py
from django.forms.widgets import TextInput,Textarea,Select,DateInput,CheckboxInput,FileInput,PasswordInput,EmailInput
from django import forms

from . models import *

        
class PropertyForm(forms.ModelForm):

    class Meta:
        model = Property
        fields = ['name','address','features','location','image']

        widgets = {
            'name': TextInput(attrs={'class': 'required form-control','placeholder' : 'Enter Name'}), 
            'address': Textarea(attrs={'class': 'required form-control text-area','placeholder' : 'Enter Address','rows':'2'}), 
            'location': TextInput(attrs={'class': 'required form-control','placeholder' : 'Enter Location'}), 
            'image': FileInput(attrs={'class': 'form-control dropify'}),
        }
        
    def clean_image(self):
        
        image_file = self.cleaned_data.get('image')
        if image_file:
            if not (image_file.name.endswith(".jpg") or image_file.name.endswith(".png") or image_file.name.endswith(".jpeg")):
                raise forms.ValidationError("Only .jpg or .png files are accepted")
        return image_file
    
class UnitForm(forms.ModelForm):

    class Meta:
        model = Unit
        fields = ['type','rent_cost','main_image']

        widgets = {
            'type': Select(attrs={'class': 'select2 form-control mb-3 custom-select'}),
            'rent_cost': TextInput(attrs={'class': 'required form-control','placeholder' : 'Enter Location'}), 
            'main_image': FileInput(attrs={'class': 'form-control dropify'}),
        }
        
    def clean_main_image(self):
        
        image_file = self.cleaned_data.get('main_image')
        if image_file:
            if not (image_file.name.endswith(".jpg") or image_file.name.endswith(".png") or image_file.name.endswith(".jpeg")):
                raise forms.ValidationError("Only .jpg or .png files are accepted")
        return image_file

property/views.py
#standerd
import json
import datetime
#django
from django.db.models import Q
from django.urls import reverse
from django.conf import settings
from django.shortcuts import render
from django.http import HttpResponse
from django.contrib.auth.models import User,Group
from django.db import transaction, IntegrityError
from django.contrib.auth.decorators import login_required
from django.forms import formset_factory, inlineformset_factory
from django.shortcuts import get_object_or_404, redirect, render
#local
from admin_user.models import AdminUser
from main.decorators import role_required
from admin_user.forms import AdminUserForm
from main.functions import encrypt_message, generate_form_errors, paginate, randomnumber
from property.forms import PropertyForm, UnitForm
from property.models import Property, Unit
from tenant.forms import TenantUnitAssignForm
from tenant.models import TenantUnitAssignment

# Create your views here.
@login_required
@role_required(['superadmin','admin_user'])
def property_list(request):
    """
    property listings
    :param request:
    :return: property list view
    """
    instances = Property.objects.filter(is_deleted=False).order_by("-id")
    
    filter_data = {}
    query = request.GET.get("q")
    
    if query:

        instances = instances.filter(
            Q(auto_id__icontains=query) |
            Q(name__icontains=query)
        )
        title = "Properties - %s" % query
        filter_data['q'] = query
          

    context = {
        'instances': instances,
        'page_name' : 'Properties',
        'page_title' : 'Properties',
        'filter_data' : filter_data
    }

    return render(request, 'admin_panel/pages/property/property_list.html', context)

@login_required
@role_required(['superadmin','admin_user'])
def property_info(request,pk):
    """
    property single view using property pk
    :param request:
    :pk
    :return: property list view
    """
    instance = Property.objects.get(pk=pk, is_deleted=False)
    units = Unit.objects.filter(property=instance,is_deleted=False)
    assigned_tenants = TenantUnitAssignment.objects.filter(unit__property=instance)
    
    context = {
        'instance': instance,
        'units' : units,
        'assigned_tenants': assigned_tenants,
        'page_name' : 'Property Details',
        'page_title' : 'Property Details',
        'is_need_light_box' : True,
    }

    return render(request, 'admin_panel/pages/property/property_info.html', context)


@login_required
@role_required(['superadmin','admin_user'])
def create_property(request):
    """
    create operation of property
    :param request:
    :return:
    """
    # check pk for getting instance    
    unitsFormset = formset_factory(UnitForm, extra=2)
    
    message = ''
    if request.method == 'POST':
        form = PropertyForm(request.POST,files=request.FILES)
        units_formset = unitsFormset(request.POST,request.FILES,prefix='units_formset', form_kwargs={'empty_permitted': False})
        
        if form.is_valid() and units_formset.is_valid():
            #create property
            data = form.save(commit=False)
            data.save()
            
            if units_formset.is_valid():
                for form in units_formset:
                    u_data = form.save(commit=False)
                    u_data.property = data
                    u_data.save()
                    
            response_data = {
                "status": "true",
                "title": "Successfully Created",
                "message": "property created successfully.",
                'redirect': 'true',
                "redirect_url": reverse('property:property_list')
            }
    
        else:
            message = generate_form_errors(form,units_formset, formset=True)
            
            response_data = {
                "status": "false",
                "title": "Failed",
                "message": message,
            }

        return HttpResponse(json.dumps(response_data), content_type='application/javascript')

    else:
        form = PropertyForm()
        units_formset = unitsFormset(prefix='units_formset')

        context = {
            'form': form,
            'units_formset': units_formset,
            
            'page_name' : 'Create property',
            'page_title' : 'Create property',
            'is_need_select2' : True,
            'url' : reverse('property:create_property'),
        }

        return render(request, 'admin_panel/pages/property/create_property.html',context)


@login_required
@role_required(['superadmin','admin_user'])
def edit_property(request,pk):
    """
    edit operation of property
    :param request:
    :param pk:
    :return:
    """
    proprty_instance = get_object_or_404(Property, pk=pk)
    unit_instance = Unit.objects.filter(property=proprty_instance,is_deleted=False)
        
    if Unit.objects.filter(product=proprty_instance).exists():
        u_extra = 0
    else:
        u_extra = 1 

    UnitFormset = inlineformset_factory(
        Property,
        Unit,
        extra=u_extra,
        form=UnitForm,
    )
        
    message = ''
    
    if request.method == 'POST':
        form = PropertyForm(request.POST,files=request.FILES,instance=proprty_instance)
        units_formset = UnitFormset(request.POST,request.FILES,
                                                             instance=proprty_instance,
                                                             prefix='units_formset',
                                                             form_kwargs={'empty_permitted': False})            
        
        if form.is_valid() and units_formset.is_valid():
            
            #create product
            data = form.save(commit=False)
            data.date_updated = datetime.datetime.today()
            data.updater = request.user
            data.save()
            
            #create multiple images
            if units_formset.is_valid():
                for form in units_formset:
                    if form not in units_formset.deleted_forms:
                        i_data = form.save(commit=False)
                        if not i_data.property :
                            i_data.property = data
                        i_data.save()

                for f in units_formset.deleted_forms:
                    f.instance.delete()
            
                response_data = {
                "status": "true",
                "title": "Successfully Updated",
                "message": "Property Updated Successfully.",
                'redirect': 'true',
                "redirect_url": reverse('product:property_list'),
                "return" : True,
            }

            else:
                response_data = {
                "status": "true",
                "title": "Successfully Updated",
                "message": "Property Updated successfully.",
                'redirect': 'true',
                "redirect_url": reverse('product:property_list'),
                "return" : False,
            }
    
        else:
            message = generate_form_errors(units_formset,formset=True)
            
            response_data = {
                "status": "false",
                "title": "Failed",
                "message": message
            }

        return HttpResponse(json.dumps(response_data), content_type='application/javascript')
                        
    else:

        form = PropertyForm(instance=proprty_instance)
        units_formset = UnitFormset(queryset=unit_instance,
                                    prefix='units_formset',
                                    instance=proprty_instance)
        
        context = {
            'form': form,
            'units_formset': units_formset,
            'message': message,
            'pro_instance': proprty_instance,
            'unit_instance': unit_instance,
            'page_name' : 'edit product',
            'url' : reverse('product:edit_property', args=[proprty_instance.pk]),            
        }

        return render(request, 'admin_panel/pages/property/create_property.html', context)


@login_required
@role_required(['superadmin','admin_user'])
def delete_property(request, pk):
    """
    property deletion, it only mark as is deleted field to true
    :param request:
    :param pk:
    :return:
    """
    Property.objects.filter(pk=pk).update(is_deleted=True)
    
    response_data = {
        "status": "true",
        "title": "Successfully Deleted",
        "message": "Property Successfully Deleted.",
        "redirect": "true",
        "redirect_url": reverse('property:property_list')
    }

    return HttpResponse(json.dumps(response_data), content_type='application/javascript')

@login_required
@role_required(['superadmin','admin_user'])
def assign_property_tenant(request, unit_id):
    """
    assign property to tenant
    :param request:
    :return:
    """
    message = ''
    
    if request.method == 'POST':
        form = TenantUnitAssignForm(request.POST,files=request.FILES)
        unit_instance = get_object_or_404(Unit, pk=unit_id)
        
        if form.is_valid() :
            data = form.save(commit=False)
            data.unit = unit_instance
            data.save()
            
            response_data = {
                "status": "true",
                "title": "Successfully Assigned",
                "message": "property assigned successfully.",
                'redirect': 'true',
                "redirect_url": reverse('property:property_info', kwargs={'pk':unit_instance.property.pk})
            }
            
        else:
            message = generate_form_errors(form, formset=False)
            
            response_data = {
                "status": "false",
                "title": "Failed",
                "message": message,
            }

        return HttpResponse(json.dumps(response_data), content_type='application/javascript')

    else:

templates/admin_panel/pages/property/property_info.html
{% extends 'admin_panel/base.html' %}
{% load static %}

{% block content %}
    <!-- Page Content-->
    <div class="page-content">
        <div class="container-fluid">
            <!-- Page-Title -->
            <div class="row">
                <div class="col-sm-12">
                    <div class="page-title-box">
                        <div class="row">
                            <div class="col">
                                <h4 class="page-title">Property Info</h4>
                                <ol class="breadcrumb">
                                    <li class="breadcrumb-item"><a href="javascript:void(0);">Dashboard</a></li>
                                    <li class="breadcrumb-item"><a href="javascript:void(0);">Property Details</a></li>
                                </ol>
                            </div><!--end col-->
                            
                        </div><!--end row-->                                                              
                    </div><!--end page-title-box-->
                </div><!--end col-->
            </div><!--end row-->
            <!-- end page title end breadcrumb -->

            <div class="row">
                <div class="col-12">
                    <div class="card">
                        <div class="card-body">
                            
                            <div class="dastone-profile border-bottom pb-4">
                                <div class="row">
                                    <div class="col-lg-4 align-self-center mb-3 mb-lg-0">
                                        <div class="dastone-profile-main">
                                            <div class="dastone-profile-main-pic">
                                                {% if instance.image %}
                                                <img src="{{instance.image.url}}" alt="" class="rounded-circle" style="height:100%;width:100%;">
                                                {% else %}
                                                <span><i class="fas fa-camera"></i></span>
                                                {% endif %}
                                            </div>
                                            <div class="dastone-profile_user-detail">
                                                <h5 class="dastone-user-name">{{instance.name}}</h5>                                                        
                                            </div>
                                        </div>                                                
                                    </div><!--end col-->
                                    
                                    <div class="col-lg-4 ml-auto align-self-center">
                                        <ul class="list-unstyled personal-detail mb-0">
                                            <li class=""><i class="las la-map-marker-alt mr-2 text-secondary font-22 align-middle"></i> <b> Location </b> : {{instance.location}}</li>
                                            <li class="mt-2"><i class="lar la-address-book text-secondary font-22 align-middle mr-2"></i> <b> Address </b> : {{instance.address}}</li>
                                        </ul>
                                       
                                    </div><!--end col-->

                                    <div class="col-lg-4 ml-auto align-self-center">
                                       
                                    </div><!--end col-->
                                </div><!--end row-->
                            </div><!--end f_profile--> 
                            <div class="media my-3">
                                <div class="media-body align-self-center ml-3 text-truncate">
                                    <h4 class="my-0 font-weight-bold">Features</h4>
                                    <p class="text-muted mt-2 font-13">{{instance.features|safe}}</p>
                                </div><!--end media-body-->
                            </div>                                                                                      
                        </div><!--end card-body-->          
                    </div> <!--end card-->    
                </div><!--end col-->
            </div><!--end row-->

            <div class="row">
                {% for u in units %}
                <div class="col-md-3">
                    <div class="card">
                        <div class="card-body">
                            <img src="{% if u.main_image %} {{u.main_image.url}} {% endif %}" alt="" class="d-block mx-auto my-4" height="150">
                            <div class="row my-4">
                                <div class="col">
                                    <a href="apps-ecommerce-products.html#" class="title-text d-block">{{u.get_type_display}} {{u.property.name}}</a>
                                </div>
                                <div class="col-auto">
                                    <h4 class="text-dark mt-0">Rs. {{u.rent_cost}}/- </h4>  
                                    <ul class="list-inline mb-0 product-review align-self-center">
                                        <li class="list-inline-item"><i class="la la-star text-warning font-16"></i></li>
                                        <li class="list-inline-item"><i class="la la-star text-warning font-16 ml-n2"></i></li>
                                        <li class="list-inline-item"><i class="la la-star text-warning font-16 ml-n2"></i></li>
                                        <li class="list-inline-item"><i class="la la-star text-warning font-16 ml-n2"></i></li>
                                        <li class="list-inline-item"><i class="la la-star-half-o text-warning font-16 ml-n2"></i></li>
                                    </ul> 
                                </div>      
                            </div> 
                            <a href="{% url 'property:assign_property_tenant' unit_id=u.pk %}"><button class="btn btn-soft-primary btn-block">Assign To</button></a>  
                        </div><!--end card-body-->
                    </div><!--end card-->
                </div><!--end col-->
                {% endfor %}
            </div>  <!--end row-->
            <div class="row">
                <div class="col-lg-12">
                    <div class="card">
                        <div class="card-header">
                            <h4 class="card-title">Assigned Tenant Details</h4>
                        </div>
                        <!--end card-header-->
                        <div class="card-body">
                            
                            <div class="table-responsive">
                                <table class="table mb-0">
                                    <thead>
                                        <tr>
                                            <th>SL.No</th>
                                            <th>Tenant Name</th>
                                            <th>Unit</th>
                                            <th>Agreement End Date</th>
                                            <th>Monthly Rent Date</th>
                                            <th class="text-right">Action</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        {% for at in assigned_tenants %}
                                        <tr>
                                            <td>{{forloop.counter}}</td>
                                            <td>{{at.tenant.name}}</td>
                                            <td>{{at.unit.get_type_display}}</td>
                                            <td>{{at.agreement_end_date}}</td>
                                            <td>{{at.monthly_rent_date}}</td>
                                                
                                            <td class="text-right">
                                                <a href="{% url 'property:property_info' pk=instance.pk %}"><i class="las la-eye text-info font-18"></i></a>
                                                <a href="{% url 'property:edit_property' pk=instance.pk %}"><i class="las la-pen text-info font-18"></i></a>
                                                <a class="action-button remove btn btn-default btn-icon" style="padding:0;"
                                                 data-id="{{instance.pk}}" data-text="{{confirm_delete_message}}" data-title="Are you sure?" href="{% url 'property:delete_property' pk=instance.pk %}"><i class="las la-trash-alt text-danger font-18"></i></a>
                                            </td>
                                        </tr>
                                        {% endfor %}
                                    </tbody>
                                </table>
                                <!--end /table-->
                            </div>
                            <!--end /tableresponsive-->
                            <!-- pagination -->
                            
                        </div>
                        <!--end card-body-->
                    </div>
                    <!--end card-->
                </div> <!-- end col -->
            </div>
            
        </div><!-- container -->
    </div>
    <!-- end page content -->
{% endblock content %}

{% block static %}
    {% load static %}
    <!-- stylessssssssssss -->
    {{form.media}}
    <style>
        .dastone-profile .dastone-profile-main .dastone-profile-main-pic {
            position: relative;
            width: 128px;
            height: 128px;
            margin-right: 18px;
            background-color: #f3f3f3;
            border-radius: 100px;
            color: #fff;
        }
        .dastone-profile-main-pic span{
            display: flex;
            align-items: center;
            justify-content: center;
            width: 100%;
            height: 100%;
            font-size: 50px;
            font-weight: 600;
        }
    </style>
    <script>
        $(document).ready(function() {
            $(".download-cv").click(function() {
                var downloadUrl = $(this).attr('data-url');  // Replace with the actual URL
                window.location.href = downloadUrl;
            });
        });
    </script>
{% endblock  %}
        

templates/admin_panel/pages/property/property_list.html
{% extends 'admin_panel/base.html' %}
{% load static %}

{% block content %}
    <!-- Page Content-->
    <div class="page-content">

        <div class="container-fluid">
            <!-- Page-Title -->
            <div class="row">
                <div class="col-sm-12">
                    <div class="page-title-box">
                        <div class="row">
                            <div class="col">
                                <h4 class="page-title">{{page_title}}</h4>
                            </div><!--end col-->
                            <div class="col-auto col-sm-2 float-right ml-auto">
                                <form method="get" action="{% url 'property:property_list' %}">
                                    <li class="list-inline-item w-100">
                                        <div class="input-group">
                                            <input name="q" type="text" placeholder="Search Name" value="{{ filter_data.q }}" class="form-control" />
                                            <span class="input-group-append">
                                                <button type="submit" class="btn btn-soft-primary btn-sm"><i class="fas fa-search"></i></button>
                                            </span>
                                        </div>
                                    </li>
                                </form>
                            </div>
                        </div><!--end row-->                                                              
                    </div><!-- end page-title-box -->
                </div><!--end col-->
            </div><!--end row-->
            <!-- end page title end breadcrumb -->

            <div class="row">
                <div class="col-lg-12">
                    <div class="card">
                        <div class="card-header">
                            <h4 class="card-title">List view</h4>
                        </div>
                        <!--end card-header-->
                        <div class="card-body">
                            
                            <div class="table-responsive">
                                <table class="table mb-0">
                                    <thead>
                                        <tr>
                                            <th>SL.No</th>
                                            <th>Name</th>
                                            <th>Location</th>
                                            <th class="text-right">Action</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        {% load el_pagination_tags %}
                                        {% paginate 20 instances %}
                                        {% for instance in instances %}
                                        <tr>
                                            <td>{{forloop.counter}}</td>
                                            <td>{{instance.name}}</td>
                                            <td>{{instance.location}}</td>
                                                
                                            <td class="text-right">
                                                <a href="{% url 'property:property_info' pk=instance.pk %}"><i class="las la-eye text-info font-18"></i></a>
                                                <a href="{% url 'property:edit_property' pk=instance.pk %}"><i class="las la-pen text-info font-18"></i></a>
                                                <a class="action-button remove btn btn-default btn-icon" style="padding:0;"
                                                 data-id="{{instance.pk}}" data-text="{{confirm_delete_message}}" data-title="Are you sure?" href="{% url 'property:delete_property' pk=instance.pk %}"><i class="las la-trash-alt text-danger font-18"></i></a>
                                            </td>
                                        </tr>
                                        {% endfor %}
                                    </tbody>
                                </table>
                                <!--end /table-->
                                {% get_pages %}
                                <div class="clearfix"></div>
                                <div class="row pagi my-3">
                                    <div class="col-sm-6 col-xs-6 text-left my-pagina">{% show_pages %}</div>
                                    <div class="col-sm-6 col-xs-6 text-right tot my-pagination align-items-center">
                                        <div class="m-t-10">
                                            Showing {{title}}
                                            <span class="current_page_index">{{ pages.current_start_index }}</span> - <span
                                                class="current_end_status">{{ pages.current_end_index }}</span> of <span
                                                class="total_count">{{ pages.total_count }}</span>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <!--end /tableresponsive-->
                            <!-- pagination -->
                            
                        </div>
                        <!--end card-body-->
                    </div>
                    <!--end card-->
                </div> <!-- end col -->
            </div>
        </div><!-- container -->
    <!-- end page content -->
{% endblock content %}

{% block static %}
    {% load static %}
    <!-- stylessssssssssss -->
    {{form.media}}

{% endblock  %}