admin_user/urls.py
from django.urls import path,re_path
from . import views

app_name = 'admin_user'

urlpatterns = [
    path('list/', views.admin_user_list, name='admin_user_list'),
    re_path(r'^create/$', views.create_admin_user, name='create_admin_user'),
    re_path(r'^info/(?P<pk>.*)/$', views.admin_user_info, name='admin_user_info'),
    re_path(r'^edit/(?P<pk>.*)/$', views.edit_admin_user, name='edit_admin_user'),
    re_path(r'^delete/(?P<pk>.*)/$', views.delete_admin_user, name='delete_admin_user'),
]

main/urls.py
from django.urls import path,re_path
from . import views

app_name = 'main'

urlpatterns = [
    path('', views.index,name='index'),
]

real_estate/urls.py
from django.contrib import admin
from django.urls import path
from django.views.static import serve
from django.urls import  include, path, re_path

from real_estate import settings
from main import views as general_views

urlpatterns = [
    path('',include(('main.urls'),namespace='main')),
    path('admin/', admin.site.urls),
    path('app/accounts/', include('registration.backends.default.urls')),
    path('super-admin/main/',general_views.app,name='app'),
    
    path('super-admin/admin-user/',include(('admin_user.urls'),namespace='admin_user')),
    path('super-admin/property/',include(('property.urls'),namespace='property')),
    path('super-admin/tenant/',include(('tenant.urls'),namespace='tenant')),
    
    re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
    re_path(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT})
]

admin_user/models.py
import uuid

from django.db import models
from django.contrib.auth.models import User

from versatileimagefield.fields import VersatileImageField

# Create your models here.
class AdminUser(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    first_name = models.CharField(max_length=200)
    last_name = models.CharField(max_length=200)
    email = models.EmailField()
    phone = models.CharField(max_length=10)
    date_of_birth = models.DateField()
    password = models.CharField(max_length=256,null=True,blank=True)
    image = VersatileImageField('Image', upload_to="admin_user/profile_pic", blank=True, null=True)
    is_deleted = models.BooleanField(default=False)
    
    user = models.OneToOneField(User,on_delete=models.CASCADE,blank=True,null=True)
    
    class Meta:
        db_table = 'admin_user'
        verbose_name = ('Admin User')
        verbose_name_plural = ('Admin User')
        
    def __str__(self):
        return f'{self.first_name} {self.last_name}'
    
    def get_fullname(self):
        return f'{self.first_name} {self.last_name}'
    
    def get_initial(self):
        first_name = self.first_name[0] if self.first_name else ''
        last_name = self.last_name[0] if self.last_name else ''
        return first_name.upper() + last_name.upper()

admin_user/forms.py
from django.forms.widgets import TextInput,Textarea,Select,DateInput,CheckboxInput,FileInput,PasswordInput,EmailInput
from django import forms
from . models import *

        
class AdminUserForm(forms.ModelForm):

    class Meta:
        model = AdminUser
        fields = ['first_name','last_name','email','phone','date_of_birth','image','password']

        widgets = {
            'first_name': TextInput(attrs={'class': 'required form-control','placeholder' : 'Enter First Name'}), 
            'last_name': TextInput(attrs={'class': 'required form-control','placeholder' : 'Enter Last Name'}), 
            'email': EmailInput(attrs={'class': 'required form-control','placeholder' : 'Enter Email'}), 
            'phone': TextInput(attrs={'class': 'required form-control','placeholder' : 'Enter Phone Number'}), 
            'date_of_birth': TextInput(attrs={'class': 'required form-control','id':'date_of_birth','name':'birthday','placeholder' : 'Enter Date of Birth'}), 
            'image': FileInput(attrs={'class': 'form-control dropify'}),
            'password': PasswordInput(attrs={'class': 'required form-control','placeholder' : 'Enter Password'}), 
        }
        
    def clean_image(self):
        
        image_file = self.cleaned_data.get('image')
        if image_file:
            if not (image_file.name.endswith(".jpg") or image_file.name.endswith(".png") or image_file.name.endswith(".jpeg")):
                raise forms.ValidationError("Only .jpg or .png files are accepted")
        return image_file

admin_user/views.py
#standerd
import json
import datetime
#django
from django.db.models import Q
from django.urls import reverse
from django.conf import settings
from django.shortcuts import render
from django.http import HttpResponse
from django.contrib.auth.models import User,Group
from django.db import transaction, IntegrityError
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404, redirect, render
#local
from admin_user.models import AdminUser
from main.decorators import role_required
from admin_user.forms import AdminUserForm
from main.functions import encrypt_message, generate_form_errors, paginate, randomnumber

# Create your views here.
@login_required
@role_required(['superadmin','admin_user'])
def admin_user_info(request,pk):
    """
    Admin User info
    :param request:
    :return: Admin User info view
    """
    instance = AdminUser.objects.get(pk=pk,is_deleted=False)

    context = {
        'instance': instance,
        'page_name' : 'Admin User',
        'page_title' : 'Admin User',
    }

    return render(request, 'admin_panel/pages/admin_user/user_info.html', context)

@login_required
@role_required(['superadmin','admin_user'])
def admin_user_list(request):
    """
    Admin User listings
    :param request:
    :return: Admin User list view
    """
    instances = AdminUser.objects.filter(is_deleted=False).order_by("-id")
    
    filter_data = {}
    query = request.GET.get("q")
    
    if query:

        instances = instances.filter(
            Q(first_name__icontains=query) |
            Q(last_name__icontains=query) 
        )
        title = "AdminUser - %s" % query
        filter_data['q'] = query

    context = {
        'instances': instances,
        'page_name' : 'Admin User',
        'page_title' : 'Admin User',
        'filter_data' :filter_data,
    }

    return render(request, 'admin_panel/pages/admin_user/user_list.html', context)

@login_required
@role_required(['superadmin','admin_user'])
def create_admin_user(request):
    """
    create operation of AdminUser
    :param request:
    :param pk:
    :return:
    """
    if request.method == 'POST':
        # if instance go to edit
        form = AdminUserForm(request.POST)
            
        if form.is_valid():
            try:
                with transaction.atomic():
                    
                    email = form.cleaned_data['email']
                    password = form.cleaned_data['password']
                    
                    user_data = User.objects.create_user(
                        username=email,
                        password=password,
                        is_active=True,
                    )
                    
                    if Group.objects.filter(name="admin_user").exists():
                        group = Group.objects.get(name="admin_user")
                    else:
                        group = Group.objects.create(name="admin_user")

                    user_data.groups.add(group)
                    
                    data = form.save(commit=False)
                    data.user = user_data
                    data.password = encrypt_message(password)
                    data.save()
                    
                    response_data = {
                        "status": "true",
                        "title": "Successfully Created",
                        "message": "Admin User created successfully.",
                        'redirect': 'true',
                        "redirect_url": reverse('admin_user:admin_user_list')
                    }
                    
            except IntegrityError as e:
                # Handle database integrity error
                response_data = {
                    "status": "false",
                    "title": "Failed",
                    "message": "Integrity error occurred. Please check your data.",
                }

            except Exception as e:
                # Handle other exceptions
                response_data = {
                    "status": "false",
                    "title": "Failed",
                    "message": str(e),
                }
            
        else:
            message =generate_form_errors(form , formset=False)
            response_data = {
                "status": "false",
                "title": "Failed",
                "message": message,
            }

        return HttpResponse(json.dumps(response_data), content_type='application/javascript')
    
    else:
        
        form = AdminUserForm()

        context = {
            'form': form,
            'page_name' : 'Create Admin User',
            'page_title' : 'Create Admin User',
            'url' : reverse('admin_user:create_admin_user'),
            
            'is_need_datetime_picker': True,
            'is_need_forms': True,
        }

        return render(request, 'admin_panel/pages/create/create.html',context)
    
@login_required
@role_required(['superadmin','admin_user'])
def edit_admin_user(request,pk):
    """
    edit operation of admin_user
    :param request:
    :param pk:
    :return:
    """
    instance = get_object_or_404(AdminUser, pk=pk)
        
    message = ''
    if request.method == 'POST':
        form = AdminUserForm(request.POST,files=request.FILES,instance=instance)
        
        if form.is_valid():
            #update AdminUser
            data = form.save(commit=False)
            data.date_updated = datetime.datetime.today()
            data.updater = request.user
            data.save()
            form.save_m2m()
                    
            response_data = {
                "status": "true",
                "title": "Successfully Created",
                "message": "Admin User Update successfully.",
                'redirect': 'true',
                "redirect_url": reverse('admin_user:admin_user_list')
            }
    
        else:
            message = generate_form_errors(form ,formset=False)
            
            response_data = {
                "status": "false",
                "title": "Failed",
                "message": message
            }

        return HttpResponse(json.dumps(response_data), content_type='application/javascript')
    
    else:
        
        form = AdminUserForm(instance=instance)

        context = {
            'form': form,
            'page_name' : 'Update Admin User',
            'page_title' : 'Update Admin User',
            'url' : reverse('admin_user:edit_admin_user', kwargs={'pk': pk}),
            
            'is_need_datetime_picker': True,
            'is_need_forms': True,
        }

        return render(request, 'admin_panel/pages/create/create.html',context)

@login_required
@role_required(['superadmin','admin_user'])
def delete_admin_user(request, pk):
    """
    AdminUser deletion, it only mark as is deleted field to true
    :param request:
    :param pk:
    :return:
    """
    instance = AdminUser.objects.get(pk=pk)
    current_email = instance.email
    append_email = current_email + str(randomnumber(3)) + "_deleted"
    
    instance.email = append_email
    instance.phone = randomnumber(5)
    instance.is_deleted = True
    instance.save()
    
    user = User.objects.get(username=current_email)
    user.username = append_email
    user.save()
    
    response_data = {
        "status": "true",
        "title": "Successfully Deleted",
        "message": "Admin User Successfully Deleted.",
        "redirect": "true",
        "redirect_url": reverse('admin_user:admin_user_list'),
    }

    return HttpResponse(json.dumps(response_data), content_type='application/javascript')

templates/admin_panel/pages/admin_user/user_info.html
{% extends 'admin_panel/base.html' %}
{% load static %}

{% block content %}
    <!-- Page Content-->
    <div class="page-content">
        <div class="container-fluid">
            <!-- Page-Title -->
            <div class="row">
                <div class="col-sm-12">
                    <div class="page-title-box">
                        <div class="row">
                            <div class="col">
                                <h4 class="page-title">User Details</h4>
                                <ol class="breadcrumb">
                                    <li class="breadcrumb-item"><a href="javascript:void(0);">Dashboard</a></li>
                                    <li class="breadcrumb-item"><a href="javascript:void(0);">User Details</a></li>
                                </ol>
                            </div><!--end col-->
                            
                        </div><!--end row-->                                                              
                    </div><!--end page-title-box-->
                </div><!--end col-->
            </div><!--end row-->
            <!-- end page title end breadcrumb -->

            <div class="row">
                <div class="col-12">
                    <div class="card">
                        <div class="card-body">
                            <div class="dastone-profile">
                                <div class="row">
                                    <div class="col-lg-4 align-self-center mb-3 mb-lg-0">
                                        <div class="dastone-profile-main">
                                            <div class="dastone-profile-main-pic">
                                                {% if instance.image %}
                                                <img src="{{instance.image.url}}" alt="" class="rounded-circle" style="height:100%;width:100%;">
                                                {% else %}
                                                <span>{{instance.get_initial}}</span>
                                                {% endif %}
                                                <span class="dastone-profile_main-pic-change">
                                                    <i class="fas fa-camera"></i>
                                                </span>
                                            </div>
                                            <div class="dastone-profile_user-detail">
                                                <h5 class="dastone-user-name">{{instance.get_fullname}}</h5>                                                        
                                            </div>
                                        </div>                                                
                                    </div><!--end col-->
                                    
                                    <div class="col-lg-4 ml-auto align-self-center">
                                        <ul class="list-unstyled personal-detail mb-0">
                                            <li class=""><i class="las la-phone mr-2 text-secondary font-22 align-middle"></i> <b> Phone </b> : {{instance.phone}}</li>
                                            <li class="mt-2"><i class="las la-envelope text-secondary font-22 align-middle mr-2"></i> <b> Email </b> : {{instance.email}}</li>
                                            <li class="mt-2"><i class="far fa-calendar-alt text-secondary font-22 align-middle mr-2"></i> <b> Date of Birth </b> : {{instance.date_of_birth}}</li>                                                   
                                        </ul>
                                       
                                    </div><!--end col-->

                                    <div class="col-lg-4 ml-auto align-self-center">
                                       
                                    </div><!--end col-->
                                </div><!--end row-->
                            </div><!--end f_profile-->                                                                                
                        </div><!--end card-body-->          
                    </div> <!--end card-->    
                </div><!--end col-->
            </div><!--end row-->
            
        </div><!-- container -->
    </div>
    <!-- end page content -->
{% endblock content %}

{% block static %}
    {% load static %}
    <!-- stylessssssssssss -->
    {{form.media}}
    <style>
        .dastone-profile .dastone-profile-main .dastone-profile-main-pic {
            position: relative;
            width: 128px;
            height: 128px;
            margin-right: 18px;
            background-color: #f3f3f3;
            border-radius: 100px;
            color: #fff;
        }
        .dastone-profile-main-pic span{
            display: flex;
            align-items: center;
            justify-content: center;
            width: 100%;
            height: 100%;
            font-size: 50px;
            font-weight: 600;
        }
    </style>
    <script>
        $(document).ready(function() {
            $(".download-cv").click(function() {
                var downloadUrl = $(this).attr('data-url');  // Replace with the actual URL
                window.location.href = downloadUrl;
            });
        });
    </script>
{% endblock  %}
        

templates/admin_panel/pages/admin_user/user_list.html
{% extends 'admin_panel/base.html' %}
{% load static %}

{% block content %}
    <!-- Page Content-->
    <div class="page-content">

        <div class="container-fluid">
            <!-- Page-Title -->
            <div class="row">
                <div class="col-sm-12">
                    <div class="page-title-box">
                        <div class="row">
                            <div class="col">
                                <h4 class="page-title">{{page_title}}</h4>
                            </div><!--end col-->
                            <div class="col-auto col-sm-2 float-right ml-auto">
                                <form method="get" action="{% url 'admin_user:admin_user_list' %}">
                                    <li class="list-inline-item w-100">
                                        <div class="input-group">
                                            <input name="q" type="text" placeholder="Search Name" value="{{ filter_data.q }}" class="form-control" />
                                            <span class="input-group-append">
                                                <button type="submit" class="btn btn-soft-primary btn-sm"><i class="fas fa-search"></i></button>
                                            </span>
                                        </div>
                                    </li>
                                </form>
                            </div>
                        </div><!--end row-->                                                              
                    </div><!-- end page-title-box -->
                </div><!--end col-->
            </div><!--end row-->
            <!-- end page title end breadcrumb -->

            <div class="row">
                <div class="col-lg-12">
                    <div class="card">
                        <div class="card-header">
                            <h4 class="card-title">List view</h4>
                        </div>
                        <!--end card-header-->
                        <div class="card-body">
                            
                            <div class="table-responsive">
                                <table class="table mb-0">
                                    <thead>
                                        <tr>
                                            <th>SL.No</th>
                                            <th>First Name</th>
                                            <th>Last Name</th>
                                            <th>Email</th>
                                            <th>Phone</th>
                                            <th>date_of_birth</th>
                                            <th class="text-right">Action</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        {% load el_pagination_tags %}
                                        {% paginate 20 instances %}
                                        {% for instance in instances %}
                                        <tr>
                                            <td>{{forloop.counter}}</td>
                                            <td>{{instance.first_name}}</td>
                                            <td>{{instance.last_name}}</td>
                                            <td>{{instance.email}}</td>
                                            <td>{{instance.phone}}</td>
                                            <td>{{instance.date_of_birth}}</td>
                                                
                                            <td class="text-right">
                                                <a href="{% url 'admin_user:admin_user_info' pk=instance.pk %}"><i class="las la-eye text-info font-18"></i></a>
                                                <a href="{% url 'admin_user:edit_admin_user' pk=instance.pk %}"><i class="las la-pen text-info font-18"></i></a>
                                                <a class="action-button remove btn btn-default btn-icon" style="padding:0;"
                                                 data-id="{{instance.pk}}" data-text="{{confirm_delete_message}}" data-title="Are you sure?" href="{% url 'admin_user:delete_admin_user' pk=instance.pk %}"><i class="las la-trash-alt text-danger font-18"></i></a>
                                            </td>
                                        </tr>
                                        {% endfor %}
                                    </tbody>
                                </table>
                                <!--end /table-->
                                {% get_pages %}
                                <div class="clearfix"></div>
                                <div class="row pagi my-3">
                                    <div class="col-sm-6 col-xs-6 text-left my-pagina">{% show_pages %}</div>
                                    <div class="col-sm-6 col-xs-6 text-right tot my-pagination align-items-center">
                                        <div class="m-t-10">
                                            Showing {{title}}
                                            <span class="current_page_index">{{ pages.current_start_index }}</span> - <span
                                                class="current_end_status">{{ pages.current_end_index }}</span> of <span
                                                class="total_count">{{ pages.total_count }}</span>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <!--end /tableresponsive-->
                            <!-- pagination -->
                            
                        </div>
                        <!--end card-body-->
                    </div>
                    <!--end card-->
                </div> <!-- end col -->
            </div>
        </div><!-- container -->
    <!-- end page content -->
{% endblock content %}

{% block static %}
    {% load static %}
    <!-- stylessssssssssss -->
    {{form.media}}

{% endblock  %}