main/urls.py
from django.urls import path,re_path
from . import views

app_name = 'main'

urlpatterns = [
    path('', views.index,name='index'),
]

real_estate/urls.py
from django.contrib import admin
from django.urls import path
from django.views.static import serve
from django.urls import  include, path, re_path

from real_estate import settings
from main import views as general_views

urlpatterns = [
    path('',include(('main.urls'),namespace='main')),
    path('admin/', admin.site.urls),
    path('app/accounts/', include('registration.backends.default.urls')),
    path('super-admin/main/',general_views.app,name='app'),
    
    path('super-admin/admin-user/',include(('admin_user.urls'),namespace='admin_user')),
    path('super-admin/property/',include(('property.urls'),namespace='property')),
    path('super-admin/tenant/',include(('tenant.urls'),namespace='tenant')),
    
    re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
    re_path(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT})
]

tenant/urls.py
from django.urls import path,re_path
from . import views

app_name = 'tenant'

urlpatterns = [
    path('list/', views.tenant_list, name='tenant_list'),
    re_path(r'^create-tenant/$', views.create_tenant, name='create_tenant'),
    re_path(r'^tenant-info/(?P<pk>.*)/$', views.tenant_info, name='tenant_info'),
    re_path(r'^edit-tenant/(?P<pk>.*)/$', views.edit_tenant, name='edit_tenant'),
    re_path(r'^delete-tenant/(?P<pk>.*)/$', views.delete_tenant, name='delete_tenant'),
]

tenant/models.py
import uuid
from django.db import models

from decimal import Decimal
from versatileimagefield.fields import VersatileImageField

from property.models import Unit

DOCUMENT_TYPES = (
    ('010', 'Adhar Card'),
    ('015', 'Driving Licence'),
    ('020', 'Voter ID'),
    ('025', 'Passport'),
)

# Create your models here.
class Tenant(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    name = models.CharField(max_length=200)
    address = models.TextField()
    image = VersatileImageField('Image', upload_to="propertes/property", blank=True, null=True)
    is_deleted = models.BooleanField(default=False)
    
    class Meta:
        db_table = 'tenant'
        verbose_name = ('Tenant')
        verbose_name_plural = ('Tenant')
        
    def __str__(self):
        return str(self.name)
    
class TenantDocuments(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    name = models.CharField(max_length=3, choices=DOCUMENT_TYPES)
    document = models.FileField(upload_to="tenant/document")
    is_deleted = models.BooleanField(default=False)
    
    tenant = models.ForeignKey(Tenant,on_delete=models.CASCADE)
    
    class Meta:
        db_table = 'tenant_documents'
        verbose_name = ('Tenant Documents')
        verbose_name_plural = ('Tenant Documents')
        
    def __str__(self):
        return str(self.id)
    
class TenantUnitAssignment(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    agreement_end_date = models.DateTimeField()
    monthly_rent_date = models.CharField(max_length=2)
    attachement = models.FileField(upload_to="tenant_unit/document",null=True,blank=True)
    is_deleted = models.BooleanField(default=False)
    
    tenant = models.ForeignKey(Tenant,on_delete=models.CASCADE)
    unit = models.ForeignKey(Unit,on_delete=models.CASCADE)
    
    class Meta:
        db_table = 'tenant_assigned_unit'
        verbose_name = ('Tenant Assigned Unit')
        verbose_name_plural = ('Tenant Assigned Unit')
        
    def __str__(self):
        return str(self.id)

tenant/forms.py
from django.forms.widgets import TextInput,Textarea,Select,DateInput,CheckboxInput,FileInput,PasswordInput,EmailInput
from django import forms

from . models import *


class TenantForm(forms.ModelForm):

    class Meta:
        model = Tenant
        fields = ['name','address','image']

        widgets = {
            'name': TextInput(attrs={'class': 'required form-control','placeholder' : 'Enter Name'}), 
            'address': Textarea(attrs={'class': 'required form-control text-area','placeholder' : 'Enter Address','rows':'2'}), 
            'image': FileInput(attrs={'class': 'form-control dropify'}),
        }
        
    def clean_image(self):
        
        image_file = self.cleaned_data.get('image')
        if image_file:
            if not (image_file.name.endswith(".jpg") or image_file.name.endswith(".png") or image_file.name.endswith(".jpeg")):
                raise forms.ValidationError("Only .jpg or .png files are accepted")
        return image_file
    
    
class TenantDocumentForm(forms.ModelForm):

    class Meta:
        model = TenantDocuments
        fields = ['name','document']

        widgets = {
            'name': Select(attrs={'class': 'select2 form-control mb-3 custom-select'}),
            'document': FileInput(attrs={'class': 'form-control dropify'}),
        }
    
        
class TenantUnitAssignForm(forms.ModelForm):

    class Meta:
        model = TenantUnitAssignment
        fields = ['tenant','agreement_end_date','monthly_rent_date','attachement']

        widgets = {
            'tenant': Select(attrs={'class': 'select2 form-control mb-3 custom-select'}),
            'agreement_end_date': TextInput(attrs={'class': 'required form-control','placeholder' : 'Enter Agrement End Date'}), 
            'monthly_rent_date': TextInput(attrs={'class': 'required form-control','placeholder' : 'Enter Rent Date'}), 
            'attachement': FileInput(attrs={'class': 'form-control dropify'}),
        }

tenant/views.py
#standerd
import json
import datetime
#django
from django.db.models import Q
from django.urls import reverse
from django.conf import settings
from django.shortcuts import render
from django.http import HttpResponse
from django.contrib.auth.models import User,Group
from django.db import transaction, IntegrityError
from django.contrib.auth.decorators import login_required
from django.forms import formset_factory, inlineformset_factory
from django.shortcuts import get_object_or_404, redirect, render
#local
from main.decorators import role_required
from main.functions import encrypt_message, generate_form_errors, paginate, randomnumber
from property.models import Unit
from tenant.forms import TenantForm, TenantDocumentForm, TenantUnitAssignForm
from tenant.models import Tenant, TenantDocuments, TenantUnitAssignment

# Create your views here.
@login_required
@role_required(['superadmin','admin_user'])
def tenant_list(request):
    """
    tenant listings
    :param request:
    :return: tenant list view
    """
    instances = Tenant.objects.filter(is_deleted=False).order_by("-id")
    
    filter_data = {}
    query = request.GET.get("q")
    
    if query:

        instances = instances.filter(
            Q(auto_id__icontains=query) |
            Q(name__icontains=query)
        )
        title = "Tenants - %s" % query
        filter_data['q'] = query
          

    context = {
        'instances': instances,
        'page_name' : 'Tenants',
        'page_title' : 'Tenants',
        'filter_data' : filter_data
    }

    return render(request, 'admin_panel/pages/tenant/tenant_list.html', context)

@login_required
@role_required(['superadmin','admin_user'])
def tenant_info(request,pk):
    """
    tenant single view using tenant pk
    :param request:
    :pk
    :return: tenant list view
    """
    instance = Tenant.objects.get(pk=pk, is_deleted=False)
    documents = TenantDocuments.objects.filter(tenant=instance,is_deleted=False)
    
    context = {
        'instance': instance,
        'documents' : documents,
        'page_name' : 'Tenant Details',
        'page_title' : 'Tenant Details',
        'is_need_light_box' : True,
    }

    return render(request, 'admin_panel/pages/tenant/tenant_info.html', context)


@login_required
@role_required(['superadmin','admin_user'])
def create_tenant(request):
    """
    create operation of tenant
    :param request:
    :return:
    """
    # check pk for getting instance    
    unitsFormset = formset_factory(TenantDocumentForm, extra=2)
    
    message = ''
    if request.method == 'POST':
        form = TenantForm(request.POST,files=request.FILES)
        tenant_document_formset = unitsFormset(request.POST,request.FILES,prefix='tenant_document_formset', form_kwargs={'empty_permitted': False})
        
        if form.is_valid() and tenant_document_formset.is_valid():
            try:
                with transaction.atomic():
                    #create tenant
                    data = form.save(commit=False)
                    data.save()
                    
                    if tenant_document_formset.is_valid():
                        for form in tenant_document_formset:
                            u_data = form.save(commit=False)
                            u_data.tenant = data
                            u_data.save()
                    
                    response_data = {
                        "status": "true",
                        "title": "Successfully Created",
                        "message": "tenant created successfully.",
                        'redirect': 'true',
                        "redirect_url": reverse('tenant:tenant_list')
                    }
                    
            except IntegrityError as e:
                # Handle database integrity error
                response_data = {
                    "status": "false",
                    "title": "Failed",
                    "message": "Integrity error occurred. Please check your data.",
                }

            except Exception as e:
                # Handle other exceptions
                response_data = {
                    "status": "false",
                    "title": "Failed",
                    "message": str(e),
                }
        else:
            message = generate_form_errors(form,tenant_document_formset, formset=True)
            
            response_data = {
                "status": "false",
                "title": "Failed",
                "message": message,
            }

        return HttpResponse(json.dumps(response_data), content_type='application/javascript')

    else:
        form = TenantForm()
        tenant_document_formset = unitsFormset(prefix='tenant_document_formset')

        context = {
            'form': form,
            'tenant_document_formset': tenant_document_formset,
            
            'page_name' : 'Create Tenant',
            'page_title' : 'Create Tenant',
            'is_need_select2' : True,
            'url' : reverse('tenant:create_tenant'),
        }

        return render(request, 'admin_panel/pages/tenant/create_tenant.html',context)


@login_required
@role_required(['superadmin','admin_user'])
def edit_tenant(request,pk):
    """
    edit operation of tenant
    :param request:
    :param pk:
    :return:
    """
    tenant_instance = get_object_or_404(Tenant, pk=pk)
    tenant_documents_instances = TenantDocuments.objects.filter(tenant=tenant_instance,is_deleted=False)
        
    if TenantDocuments.objects.filter(tenant=tenant_instance).exists():
        t_extra = 0
    else:
        t_extra = 1 

    UnitFormset = inlineformset_factory(
        Tenant,
        TenantDocuments,
        extra=t_extra,
        form=TenantDocumentForm,
    )
        
    message = ''
    
    if request.method == 'POST':
        form = TenantForm(request.POST,files=request.FILES,instance=tenant_instance)
        tenant_document_formset = UnitFormset(request.POST,request.FILES,
                                            instance=tenant_instance,
                                            prefix='tenant_document_formset',
                                            form_kwargs={'empty_permitted': False})            
        
        if form.is_valid() and tenant_document_formset.is_valid():
            
            #create tenant
            data = form.save(commit=False)
            data.date_updated = datetime.datetime.today()
            data.updater = request.user
            data.save()
            
            #create multiple images
            if tenant_document_formset.is_valid():
                for form in tenant_document_formset:
                    if form not in tenant_document_formset.deleted_forms:
                        i_data = form.save(commit=False)
                        if not i_data.tenant :
                            i_data.tenant = data
                        i_data.save()

                for f in tenant_document_formset.deleted_forms:
                    f.instance.delete()
            
                response_data = {
                "status": "true",
                "title": "Successfully Updated",
                "message": "Tenant Updated Successfully.",
                'redirect': 'true',
                "redirect_url": reverse('tenant:tenant_list'),
                "return" : True,
            }

            else:
                response_data = {
                "status": "true",
                "title": "Successfully Updated",
                "message": "Tenant Updated successfully.",
                'redirect': 'true',
                "redirect_url": reverse('tenant:tenant_list'),
                "return" : False,
            }
    
        else:
            message = generate_form_errors(tenant_document_formset,formset=True)
            
            response_data = {
                "status": "false",
                "title": "Failed",
                "message": message
            }

        return HttpResponse(json.dumps(response_data), content_type='application/javascript')
                        
    else:

        form = TenantForm(instance=tenant_instance)
        tenant_document_formset = UnitFormset(queryset=tenant_documents_instances,
                                    prefix='tenant_document_formset',
                                    instance=tenant_instance)
        
        context = {
            'form': form,
            'tenant_document_formset': tenant_document_formset,
            'message': message,
            'tenant_instance': tenant_instance,
            'tenant_documents_instances': tenant_documents_instances,
            'page_name' : 'edit tenant',
            'url' : reverse('tenant:edit_tenant', args=[tenant_instance.pk]),            
        }

        return render(request, 'admin_panel/pages/tenant/create_tenant.html', context)


@login_required
@role_required(['superadmin','admin_user'])
def delete_tenant(request, pk):
    """
    tenant deletion, it only mark as is deleted field to true
    :param request:
    :param pk:
    :return:
    """
    Tenant.objects.filter(pk=pk).update(is_deleted=True)
    
    response_data = {
        "status": "true",
        "title": "Successfully Deleted",
        "message": "Tenant Successfully Deleted.",
        "redirect": "true",
        "redirect_url": reverse('tenant:tenant_list')
    }

    return HttpResponse(json.dumps(response_data), content_type='application/javascript')

templates/admin_panel/pages/tenant/tenant_info.html
{% extends 'admin_panel/base.html' %}
{% load static %}

{% block content %}
    <!-- Page Content-->
    <div class="page-content">
        <div class="container-fluid">
            <!-- Page-Title -->
            <div class="row">
                <div class="col-sm-12">
                    <div class="page-title-box">
                        <div class="row">
                            <div class="col">
                                <h4 class="page-title">Tenant Info</h4>
                                <ol class="breadcrumb">
                                    <li class="breadcrumb-item"><a href="javascript:void(0);">Dashboard</a></li>
                                    <li class="breadcrumb-item"><a href="javascript:void(0);">Tenant Details</a></li>
                                </ol>
                            </div><!--end col-->
                            
                        </div><!--end row-->                                                              
                    </div><!--end page-title-box-->
                </div><!--end col-->
            </div><!--end row-->
            <!-- end page title end breadcrumb -->

            <div class="row">
                <div class="col-12">
                    <div class="card">
                        <div class="card-body">
                            
                            <div class="dastone-profile border-bottom pb-4">
                                <div class="row">
                                    <div class="col-lg-4 align-self-center mb-3 mb-lg-0">
                                        <div class="dastone-profile-main">
                                            <div class="dastone-profile-main-pic">
                                                {% if instance.image %}
                                                <img src="{{instance.image.url}}" alt="" class="rounded-circle" style="height:100%;width:100%;">
                                                {% else %}
                                                <span><i class="fas fa-camera"></i></span>
                                                {% endif %}
                                            </div>
                                            <div class="dastone-profile_user-detail">
                                                <h5 class="dastone-user-name">{{instance.name}}</h5>                                                        
                                            </div>
                                        </div>                                                
                                    </div><!--end col-->
                                    
                                    <div class="col-lg-4 ml-auto align-self-center">
                                        <ul class="list-unstyled personal-detail mb-0">
                                            <li class="mt-2"><i class="lar la-address-book text-secondary font-22 align-middle mr-2"></i> <b> Address </b> : {{instance.address}}</li>
                                        </ul>
                                       
                                    </div><!--end col-->

                                    <div class="col-lg-4 ml-auto align-self-center">
                                       
                                    </div><!--end col-->
                                </div><!--end row-->
                            </div><!--end f_profile--> 
                            <div class="media my-3">
                                <div class="media-body align-self-center ml-3 text-truncate">
                                    <h4 class="my-0 font-weight-bold">Documents</h4>
                                    <div class="file-box-content mt-4">
                                        {% for d in documents %}
                                            {% if d %}
                                            {% if d.document.type == 'image' %}
                                            <img src="{{ d.document.url }}" alt="Attached Image">
                                            {% elif d.document.type == 'pdf' %}
                                            <iframe src="{{ d.document.url }}" width="100%" height="500px"></iframe>
                                            {% else %}
                                            <div class="file-box">
                                                <a href="{{ d.document.url }}" class="download-icon-link" download>
                                                    <i class="dripicons-download file-download-icon"></i>
                                                </a>
                                                <div class="text-center">
                                                    <i class="lar la-file-code text-danger"></i>
                                                    <h6 class="text-truncate">{{d.get_name_display}}</h6>
                                                </div>                                                        
                                            </div>
                                            {% endif %}
                                            {% else %}
                                            --
                                            {% endif %}

                                        
                                        {% endfor %}
                                    </div>
                                </div><!--end media-body-->
                            </div>                                                                                      
                        </div><!--end card-body-->          
                    </div> <!--end card-->    
                </div><!--end col-->
            </div><!--end row-->
            
        </div><!-- container -->
    </div>
    <!-- end page content -->
{% endblock content %}

{% block static %}
    {% load static %}
    <!-- stylessssssssssss -->
    {{form.media}}
    <style>
        .dastone-profile .dastone-profile-main .dastone-profile-main-pic {
            position: relative;
            width: 128px;
            height: 128px;
            margin-right: 18px;
            background-color: #f3f3f3;
            border-radius: 100px;
            color: #fff;
        }
        .dastone-profile-main-pic span{
            display: flex;
            align-items: center;
            justify-content: center;
            width: 100%;
            height: 100%;
            font-size: 50px;
            font-weight: 600;
        }
    </style>
    <script>
        $(document).ready(function() {
            $(".download-cv").click(function() {
                var downloadUrl = $(this).attr('data-url');  // Replace with the actual URL
                window.location.href = downloadUrl;
            });
        });
    </script>
{% endblock  %}
        

templates/admin_panel/pages/tenant/tenant_list.html
{% extends 'admin_panel/base.html' %}
{% load static %}

{% block content %}
    <!-- Page Content-->
    <div class="page-content">

        <div class="container-fluid">
            <!-- Page-Title -->
            <div class="row">
                <div class="col-sm-12">
                    <div class="page-title-box">
                        <div class="row">
                            <div class="col">
                                <h4 class="page-title">{{page_title}}</h4>
                            </div><!--end col-->
                            <div class="col-auto col-sm-2 float-right ml-auto">
                                <form method="get" action="{% url 'tenant:tenant_list' %}">
                                    <li class="list-inline-item w-100">
                                        <div class="input-group">
                                            <input name="q" type="text" placeholder="Search Name" value="{{ filter_data.q }}" class="form-control" />
                                            <span class="input-group-append">
                                                <button type="submit" class="btn btn-soft-primary btn-sm"><i class="fas fa-search"></i></button>
                                            </span>
                                        </div>
                                    </li>
                                </form>
                            </div>
                        </div><!--end row-->                                                              
                    </div><!-- end page-title-box -->
                </div><!--end col-->
            </div><!--end row-->
            <!-- end page title end breadcrumb -->

            <div class="row">
                <div class="col-lg-12">
                    <div class="card">
                        <div class="card-header">
                            <h4 class="card-title">List view</h4>
                        </div>
                        <!--end card-header-->
                        <div class="card-body">
                            
                            <div class="table-responsive">
                                <table class="table mb-0">
                                    <thead>
                                        <tr>
                                            <th>SL.No</th>
                                            <th>Name</th>
                                            <th>Address</th>
                                            <th class="text-right">Action</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        {% load el_pagination_tags %}
                                        {% paginate 20 instances %}
                                        {% for instance in instances %}
                                        <tr>
                                            <td>{{forloop.counter}}</td>
                                            <td>{{instance.name}}</td>
                                            <td>{{instance.address}}</td>
                                                
                                            <td class="text-right">
                                                <a href="{% url 'tenant:tenant_info' pk=instance.pk %}"><i class="las la-eye text-info font-18"></i></a>
                                                <a href="{% url 'tenant:edit_tenant' pk=instance.pk %}"><i class="las la-pen text-info font-18"></i></a>
                                                <a class="action-button remove btn btn-default btn-icon" style="padding:0;"
                                                 data-id="{{instance.pk}}" data-text="{{confirm_delete_message}}" data-title="Are you sure?" href="{% url 'tenant:delete_tenant' pk=instance.pk %}"><i class="las la-trash-alt text-danger font-18"></i></a>
                                            </td>
                                        </tr>
                                        {% endfor %}
                                    </tbody>
                                </table>
                                <!--end /table-->
                                {% get_pages %}
                                <div class="clearfix"></div>
                                <div class="row pagi my-3">
                                    <div class="col-sm-6 col-xs-6 text-left my-pagina">{% show_pages %}</div>
                                    <div class="col-sm-6 col-xs-6 text-right tot my-pagination align-items-center">
                                        <div class="m-t-10">
                                            Showing {{title}}
                                            <span class="current_page_index">{{ pages.current_start_index }}</span> - <span
                                                class="current_end_status">{{ pages.current_end_index }}</span> of <span
                                                class="total_count">{{ pages.total_count }}</span>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <!--end /tableresponsive-->
                            <!-- pagination -->
                            
                        </div>
                        <!--end card-body-->
                    </div>
                    <!--end card-->
                </div> <!-- end col -->
            </div>
        </div><!-- container -->
    <!-- end page content -->
{% endblock content %}

{% block static %}
    {% load static %}
    <!-- stylessssssssssss -->
    {{form.media}}

{% endblock  %}