admin_user/urls.py
from django.urls import path,re_path
from . import views

app_name = 'admin_user'

urlpatterns = [
    path('list/', views.admin_user_list, name='admin_user_list'),
    re_path(r'^create/$', views.create_admin_user, name='create_admin_user'),
    re_path(r'^info/(?P<pk>.*)/$', views.admin_user_info, name='admin_user_info'),
    re_path(r'^edit/(?P<pk>.*)/$', views.edit_admin_user, name='edit_admin_user'),
    re_path(r'^delete/(?P<pk>.*)/$', views.delete_admin_user, name='delete_admin_user'),
]

main/urls.py
from django.urls import path,re_path
from . import views

app_name = 'main'

urlpatterns = [
    path('', views.index,name='index'),
]

property/urls.py
from django.urls import path,re_path
from . import views

app_name = 'property'

urlpatterns = [
    path('list/', views.property_list, name='property_list'),
    re_path(r'^create-property/$', views.create_property, name='create_property'),
    re_path(r'^property-info/(?P<pk>.*)/$', views.property_info, name='property_info'),
    re_path(r'^edit-property/(?P<pk>.*)/$', views.edit_property, name='edit_property'),
    re_path(r'^delete-property/(?P<pk>.*)/$', views.delete_property, name='delete_property'),
    re_path(r'^assign-property/(?P<unit_id>.*)/$', views.assign_property_tenant, name='assign_property_tenant'),
]

real_estate/urls.py
from django.contrib import admin
from django.urls import path
from django.views.static import serve
from django.urls import  include, path, re_path

from real_estate import settings
from main import views as general_views

urlpatterns = [
    path('',include(('main.urls'),namespace='main')),
    path('admin/', admin.site.urls),
    path('app/accounts/', include('registration.backends.default.urls')),
    path('super-admin/main/',general_views.app,name='app'),
    
    path('super-admin/admin-user/',include(('admin_user.urls'),namespace='admin_user')),
    path('super-admin/property/',include(('property.urls'),namespace='property')),
    path('super-admin/tenant/',include(('tenant.urls'),namespace='tenant')),
    
    re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
    re_path(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT})
]

tenant/urls.py
from django.urls import path,re_path
from . import views

app_name = 'tenant'

urlpatterns = [
    path('list/', views.tenant_list, name='tenant_list'),
    re_path(r'^create-tenant/$', views.create_tenant, name='create_tenant'),
    re_path(r'^tenant-info/(?P<pk>.*)/$', views.tenant_info, name='tenant_info'),
    re_path(r'^edit-tenant/(?P<pk>.*)/$', views.edit_tenant, name='edit_tenant'),
    re_path(r'^delete-tenant/(?P<pk>.*)/$', views.delete_tenant, name='delete_tenant'),
]

templates/admin_panel/includes/sidebar/super_admin_side_bar.html
{% load static %}

<div class="left-sidenav">
    <!-- LOGO -->
    <div class="brand">
        <a href="{% url 'app' %}" class="logo">
            <span>
                <img src="" alt="logo-small" class="logo-sm" style="height: 85px;">
            </span>
        </a>
    </div>
    <!--end logo-->
    <div class="menu-content h-100" data-simplebar>
        <ul class="metismenu left-sidenav-menu">
            <li class="menu-label mt-0">Main</li>
            <li>
                <a href="{% url 'app' %}"> <i data-feather="home" class="align-self-center menu-icon"></i><span>Dashboard</span><span class="menu-arrow"><i class="mdi mdi-chevron-down"></i></span></a>
            </li>
            <li>
                <a href="javascript: void(0);"> <i data-feather="users" class="align-self-center menu-icon"></i><span>Admin Users</span><span class="menu-arrow"><i class="mdi mdi-chevron-right"></i></span></a>
                <ul class="nav-second-level" aria-expanded="false">
                    <li class="nav-item d-flex justify-content-between">
                        <a class="nav-link" href="{% url 'admin_user:admin_user_list' %}"><i class="ti-control-record"></i>Users List</a>
                        <a class="nav-link" href="{% url 'admin_user:create_admin_user' %}"><i class="ti-plus"></i></a>
                    </li>
                </ul>
            </li>
            <li>
                <a href="javascript: void(0);"> <i data-feather="users" class="align-self-center menu-icon"></i><span>Property</span><span class="menu-arrow"><i class="mdi mdi-chevron-right"></i></span></a>
                <ul class="nav-second-level" aria-expanded="false">
                    <li class="nav-item d-flex justify-content-between">
                        <a class="nav-link" href="{% url 'property:property_list' %}"><i class="ti-control-record"></i>Property List</a>
                        <a class="nav-link" href="{% url 'property:create_property' %}"><i class="ti-plus"></i></a>
                    </li>
                </ul>
            </li>
            <li>
                <a href="javascript: void(0);"> <i data-feather="users" class="align-self-center menu-icon"></i><span>Tenant</span><span class="menu-arrow"><i class="mdi mdi-chevron-right"></i></span></a>
                <ul class="nav-second-level" aria-expanded="false">
                    <li class="nav-item d-flex justify-content-between">
                        <a class="nav-link" href="{% url 'tenant:tenant_list' %}"><i class="ti-control-record"></i>Tenant List</a>
                        <a class="nav-link" href="{% url 'tenant:create_tenant' %}"><i class="ti-plus"></i></a>
                    </li>
                </ul>
            </li>
        </ul>
    </div>
</div>